-injars ../240x320-rus-zombie-infection.jar
-outjars deobfuscated.jar
-applymapping mapping.txt
-dontoptimize
-dontobfuscate
-dontshrink
-dontpreverify
-overloadaggressively
-allowaccessmodification
-dontwarn javax.microedition.**
-dontwarn java.**
-ignorewarnings
